name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mmicko/setup-oss-cad-suite@v1
        with:
          osscadsuite-version: '2021-05-26'
      - name: Run a one-line script
        run: yosys --version
